# Site wide configuration

title:            "01100001 01111001 01101111"
locale:           en_US
url:              "https://www.abeji.de"


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll/tagging
  - jekyll-tagging-related_posts

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Site owner
owner:
  name: Abejide Ayodele
  avatar: "me.jpg"
  bio: "Software Engineer"
  email: "abejideayodele@gmail.com"
  disqus-shortname: bjhaid
  twitter:  bjhaid
  facebook: #username
  google:
    plus: #username
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: bjhaid
  stackoverflow: 1020958/bjhaid
  linkedin: in/ayodele-abejide/
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
show_drafts: false
